name: Update po/pot files

on: workflow_dispatch
  # schedule:
  #  - cron: "0 9 * * *"

jobs:
  Org-Preparation:
    runs-on: ubuntu-latest
    env:
      # branch name of python-docs-ja repository
      DOCS_BRANCH: "3.10"
      # branch name of cpython repository
      CPYTHON_BRANCH: "3.10"
      # branch name of cpython-doc-catalog repository
      CATALOG_BRANCH: "catalog-3.10"
      # Transifex project name
      TRANSIFEX_PROJECT: "python-newest"
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10"
          architecture: "x64"
          
      - name: Install packages
        run: |
          pip install --upgrade sphinx
          pip install --upgrade sphinx-intl
          pip install --upgrade blurb
          pip install --upgrade transifex-client
          
      - name: Setup tx
        run: mv "${GITHUB_WORKSPACE}/files/.transifexrc" ~/.transifexrc
          
      - uses: actions/checkout@v2
      - name: Run scripts
        run: |
          # make files rnnable
          chmod +x "${GITHUB_WORKSPACE}/scripts/upload-catalog.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/renew-catalog-template.sh"
          
          # run scrits
          "${GITHUB_WORKSPACE}/scripts/upload-catalog.sh"
          "${GITHUB_WORKSPACE}/scripts/renew-catalog-template.sh"
          

      
